handlers: rework temporary file handling
Previously, we would try to read the header from /dev/null:

$ SOURCE_DATE_EPOCH=1748901600 target/debug/add-determinism --check tests/cases/jars/hello.jar
tests/cases/jars/hello.jar: failed to process: invalid Zip archive: Invalid zip header
...
Error: processing failed

The whole approach was too smart for its own good. Let's always open a
"temporary file", but open "/dev/null" if we actually don't need the file
except as an output sink. When doing --check, open a file in the temporary
directory, since we might not have write permissions in the source location.

Overall, this is simpler.