selinux: handle look_up_by_path returning ENOENT
$ target/debug/linkdupes --print-selinux-contexts /tmp/asdfasd
Error: selabel_lookup() failed
Caused by:
    No such file or directory (os error 2)

Sometimes we get <<none>>, sometimes we get an error… Let's just
hope that for the use case of files in rpms, we can get away with
being sloppy.